---
- name: Data loading in postgres DB using ansible
  hosts: localhost
  vars:
    db: mahesh
    table: wealthmanagement.users
    file: /Users/mahesh/Dev/ansible-examples/postgres-file-loading/sample-users.csv
  
  tasks:
    - name: Check if file available 
      stat:
        path: "{{ file }}"
      register: file_details
      delegate_to: localhost

    - name: Delete all the rows of table before we load it.
      command: psql -h localhost -U "{{db}}" -d "{{db}}" -c "DELETE FROM "{{table}}" ;"
      delegate_to: localhost

    - name: Load file into PostgreSQL using psql copy
      command: psql -h localhost -U "{{db}}" -d "{{db}}" -c "\copy "{{table}}" FROM "{{ file }}" DELIMITER ';' CSV HEADER";
      delegate_to: localhost
      when: file_details.stat.exists and file_details.stat.size > 0
